heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://kibana:5601

- type: icmp
  schedule: '@every 5s'
  hosts:
    - es01
    - kibana

- type: tcp
  id: es01
  name: Elasticsearch TCP
  hosts: ["es01:9200"]
  schedule: '@every 5s'

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: 'es01:9200'
  username: "elastic"
  password: "changeme"
