# For per pipeline config, check docs: https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html

- pipeline.id: main
  path.config: "/usr/share/logstash/pipeline/main.conf"
  queue.type: memory

- pipeline.id: logging
  path.config: "/usr/share/logstash/pipeline/logstash.conf"
  queue.type: persisted
  pipeline.batch.size: 125
  queue.page_capacity: 150mb
